### ISSUE TITLE
Updating the wordlist

### ISSUE THREAD

**Issue by mchlstr** [ViktorMares/ultimate_discovery#1]
Hey! I came across your article at Medium. Great article and wordlist. But since it is 2024 already, I suggest a little update with following paths 😉

2023.sql
2023.tar
2023.tar.bz2
2023.tar.gz
2023.tgz
2023.zip
2024
2024/

**Comment by ViktorMares** [comment]
Hey, thanks for the suggestion. I have updated the list :)

**Comment by mchlstr** [comment]
Wow thats was fast Victor 😁 Gl with hunting and work.
